import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DialogProvider from "@/components/DialogProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body className={inter.className}>
        <DialogProvider>{children}</DialogProvider>
      </body>
    </html>
  );
}
